shared:
  my_ci: &common_checks
    - check-success="CI / build (11, ubuntu-latest)"
    - check-success="CI / build (11, windows-latest)"
    - check-success="CI / build (11, macos-latest)"
    - check-success="CI / build (17, ubuntu-latest)"
    - check-success="CI / build (17, windows-latest)"
    - check-success="CI / build (17, macos-latest)"

queue_rules:
  - name: default
    conditions: *common_checks

pull_request_rules:
  - name: automatic merge for main when CI passes
    conditions:
      - base=main
      - or:
        - label=ready-to-merge
        - label=dependencies
      - and: *common_checks
    actions:
      queue:
        name: default
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: