name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java_version: [11, 17]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java_version }}
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v3.4.0
      with:
        arguments: check
    - name: Upload coverage reports to Codecov
      if: matrix.os == 'ubuntu-latest' && matrix.java_version == '11'
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
